export enum SyntaxKind {
  // tokens
  FirstToken,
  EOF,
  Unknown,
  // literals
  IntLiteral,
  RealLiteral,
  HexLiteral,
  StringLiteral,
  Identifier,
  TrueLiteral,
  FalseLiteral,
  // misc
  Dot,
  Semicolon,
  Colon,
  Comma,
  Bang,
  QuestionMark,
  Hash,
  At,
  // variables
  Equals,
  PlusEquals,
  MinusEquals,
  // arithmetic
  Plus,
  PlusPlus,
  Minus,
  MinusMinus,
  Star,
  Slash,
  Percent,
  // comparison
  LessThan,
  LessThanEquals,
  EqualsEquals,
  BangEquals,
  GreaterThan,
  GreaterThanEquals,
  // bitwise
  Ampersand,
  Pipe,
  AmpersandAmpersand,
  PipePipe,
  Caret,
  CaretCaret,
  LessThanLessThan,
  GreaterThanGreaterThan,
  Tilde,
  // parens
  LeftParenthesis,
  RightParenthesis,
  LeftCurlyBracket,
  RightCurlyBracket,
  LeftBracket,
  RightBracket,
  // keywords
  Var,
  Mod,
  Div,
  If,
  Else,
  Repeat,
  While,
  Do,
  Until,
  For,
  Continue,
  Switch,
  Case,
  Break,
  Default,
  Exit,
  With,
  Enum,
  Return,
  LastToken,

  // trivia
  FirstTrivia,
  LineComment,
  BlockComment,
  Whitespace,
  LastTrivia,

  // statements
  FirstStatement,
  ExpressionStatement,
  BlockStatement,
  AssignmentStatement,
  LocalDeclarationStatement,
  LocalDeclarationListStatement,
  IfStatement,
  RepeatStatement,
  WhileStatement,
  BreakStatement,
  ContinueStatement,
  ExitStatement,
  DoStatement,
  ForStatement,
  SwitchStatement,
  CaseStatement,
  DefaultStatement,
  WithStatement,
  ReturnStatement,
  LastStatement,

  // expressions
  FirstExpression,
  IntLiteralExpression,
  HexLiteralExpression,
  RealLiteralExpression,
  BoolLiteralExpression,
  StringLiteralExpression,
  BinaryExpression,
  UnaryExpression,
  PostfixExpression,
  PrefixExpression,
  ParenthesisedExpression,
  IdentifierExpression,
  PropertyAccessExpression,
  ArrayIndexExpression,
  CallExpression,
  ListAccessExpression,
  MapAccessExpression,
  GridAccessExpression,
  ArrayAccessExpression,
  LastExpression,
}
